// Local fallback catalogue used when the Supabase backend is unreachable
// (e.g. CI without secrets, offline dev). Mirrors the `ev_models`/`posts` row
// shapes so pages render exactly as they do against a live database.
import type { Database } from "@/integrations/supabase/types";

type EvModel = Database["public"]["Tables"]["ev_models"]["Row"];
type Post = Database["public"]["Tables"]["posts"]["Row"];

const TODAY = new Date().toISOString().slice(0, 10);
const CREATED = "2026-06-18T00:00:00Z";

export const LOCAL_EV_MODELS: EvModel[] = [
  {
    id: "local-seal",
    brand: "BYD",
    model: "Seal",
    slug: "seal",
    type: "EV",
    price_bdt: 8990000,
    range_km: 570,
    battery_kwh: 82.5,
    charging_time_min: 30,
    zero_to_hundred: 3.8,
    specs: {
      platform: "e-Platform 3.0",
      safety: "5-star Euro NCAP",
      airbags: 9,
      top_speed_kmh: 180,
    },
    pros: ["82.5 kWh Blade Battery", "৫-স্টার Euro NCAP", "ITAC টর্ক ভেক্টরিং"],
    cons: ["ব্র্যান্ডেড সার্ভিস নেটওয়ার্ক সীমিত"],
    image_url: null,
    is_featured: true,
    display_order: 1,
    created_at: CREATED,
    last_price_update: TODAY,
  },
  {
    id: "local-sealion-6",
    brand: "BYD",
    model: "Sealion 6",
    slug: "sealion-6",
    type: "PHEV",
    price_bdt: 6490000,
    range_km: 1092,
    battery_kwh: 18.3,
    charging_time_min: 120,
    zero_to_hundred: 5.9,
    specs: { platform: "DM-i", safety: "5-star Euro NCAP", airbags: 7, top_speed_kmh: 180 },
    pros: ["১,০৯২ কিমি কম্বাইন্ড রেঞ্জ", "DM-i প্লাগ-ইন হাইব্রিড"],
    cons: ["পেট্রোল ইঞ্জিনের সার্ভিসিং লাগে"],
    image_url: null,
    is_featured: true,
    display_order: 2,
    created_at: CREATED,
    last_price_update: TODAY,
  },
  {
    id: "local-atto-3",
    brand: "BYD",
    model: "Atto 3",
    slug: "atto-3",
    type: "EV",
    price_bdt: 5590000,
    range_km: 420,
    battery_kwh: 60.5,
    charging_time_min: 30,
    zero_to_hundred: 7.3,
    specs: {
      platform: "e-Platform 3.0",
      safety: "5-star Euro NCAP",
      airbags: 7,
      top_speed_kmh: 150,
    },
    pros: ["Blade Battery", "V2L মোবাইল পাওয়ার স্টেশন"],
    cons: ["রিয়ার স্পেস সীমিত"],
    image_url: null,
    is_featured: true,
    display_order: 3,
    created_at: CREATED,
    last_price_update: TODAY,
  },
  {
    id: "local-dolphin",
    brand: "BYD",
    model: "Dolphin",
    slug: "dolphin",
    type: "EV",
    price_bdt: 3990000,
    range_km: 340,
    battery_kwh: 60.4,
    charging_time_min: 30,
    zero_to_hundred: 9.1,
    specs: {
      platform: "e-Platform 3.0",
      safety: "5-star Euro NCAP",
      airbags: 6,
      top_speed_kmh: 150,
    },
    pros: ["সাশ্রয়ী দাম", "শহুরে ব্যবহারে ভালো রেঞ্জ"],
    cons: ["হাইওয়েতে কম ক্ষমতা"],
    image_url: null,
    is_featured: true,
    display_order: 4,
    created_at: CREATED,
    last_price_update: TODAY,
  },
  {
    id: "local-mg-4",
    brand: "MG",
    model: "MG 4",
    slug: "mg-4",
    type: "EV",
    price_bdt: 3999000,
    range_km: 435,
    battery_kwh: 64,
    charging_time_min: 35,
    zero_to_hundred: 3.8,
    specs: { platform: "MSP", safety: "5-star Euro NCAP", airbags: 6, top_speed_kmh: 160 },
    pros: ["XPilot ADAS", "৪৩৫ কিমি রেঞ্জ"],
    cons: ["ইনফোটেইনমেন্ট ধীর"],
    image_url: null,
    is_featured: true,
    display_order: 5,
    created_at: CREATED,
    last_price_update: TODAY,
  },
  {
    id: "local-hyundai-ioniq-5",
    brand: "Hyundai",
    model: "Ioniq 5",
    slug: "hyundai-ioniq-5",
    type: "EV",
    price_bdt: 6500000,
    range_km: 430,
    battery_kwh: 77.4,
    charging_time_min: 18,
    zero_to_hundred: 5.2,
    specs: { platform: "E-GMP", safety: "5-star Euro NCAP", airbags: 7, top_speed_kmh: 185 },
    pros: ["৮০০V আল্ট্রা-ফাস্ট চার্জিং", "V2L"],
    cons: ["দাম তুলনামূলক বেশি"],
    image_url: null,
    is_featured: true,
    display_order: 6,
    created_at: CREATED,
    last_price_update: TODAY,
  },
  {
    id: "local-kia-ev6",
    brand: "Kia",
    model: "EV6",
    slug: "kia-ev6",
    type: "EV",
    price_bdt: 8500000,
    range_km: 528,
    battery_kwh: 77.4,
    charging_time_min: 18,
    zero_to_hundred: 5.2,
    specs: { platform: "E-GMP", safety: "5-star Euro NCAP", airbags: 7, top_speed_kmh: 185 },
    pros: ["৮০০V আর্কিটেকচার", "GT-line স্টাইলিং"],
    cons: ["আমদানি শুল্কে দাম বেশি"],
    image_url: null,
    is_featured: false,
    display_order: 7,
    created_at: CREATED,
    last_price_update: TODAY,
  },
  {
    id: "local-tesla-model-y",
    brand: "Tesla",
    model: "Model Y",
    slug: "tesla-model-y",
    type: "EV",
    price_bdt: 9500000,
    range_km: 565,
    battery_kwh: 75,
    charging_time_min: 20,
    zero_to_hundred: 5.0,
    specs: {
      platform: "3rd-gen platform",
      safety: "5-star Euro NCAP",
      airbags: 8,
      top_speed_kmh: 217,
    },
    pros: ["সুপারচার্জার নেটওয়ার্ক", "Sentry Mode"],
    cons: ["অনানুষ্ঠানিক আমদানি — ওয়ারেন্টি সীমিত"],
    image_url: null,
    is_featured: false,
    display_order: 8,
    created_at: CREATED,
    last_price_update: TODAY,
  },
  {
    id: "local-tesla-model-3",
    brand: "Tesla",
    model: "Model 3",
    slug: "tesla-model-3",
    type: "EV",
    price_bdt: 8500000,
    range_km: 629,
    battery_kwh: 75,
    charging_time_min: 20,
    zero_to_hundred: 4.4,
    specs: {
      platform: "3rd-gen platform",
      safety: "5-star Euro NCAP",
      airbags: 8,
      top_speed_kmh: 201,
    },
    pros: ["সবচেয়ে দীর্ঘ রেঞ্জ", "Autopilot"],
    cons: ["অনানুষ্ঠানিক আমদানি — ওয়ারেন্টি সীমিত"],
    image_url: null,
    is_featured: false,
    display_order: 9,
    created_at: CREATED,
    last_price_update: TODAY,
  },
  {
    id: "local-mg-zs-ev",
    brand: "MG",
    model: "ZS EV",
    slug: "mg-zs-ev",
    type: "EV",
    price_bdt: 4250000,
    range_km: 320,
    battery_kwh: 72.6,
    charging_time_min: 35,
    zero_to_hundred: 8.2,
    specs: { platform: "ZS platform", safety: "5-star Euro NCAP", airbags: 6, top_speed_kmh: 140 },
    pros: ["পরিবারের জন্য উপযুক্ত SUV"],
    cons: ["রেঞ্জ তুলনামূলক কম"],
    image_url: null,
    is_featured: false,
    display_order: 10,
    created_at: CREATED,
    last_price_update: TODAY,
  },
  {
    id: "local-hyundai-kona-electric",
    brand: "Hyundai",
    model: "Kona Electric",
    slug: "hyundai-kona-electric",
    type: "EV",
    price_bdt: 5000000,
    range_km: 484,
    battery_kwh: 64,
    charging_time_min: 47,
    zero_to_hundred: 7.9,
    specs: { platform: "K2 platform", safety: "5-star Euro NCAP", airbags: 6, top_speed_kmh: 155 },
    pros: ["দীর্ঘ রেঞ্জ", "নির্ভরযোগ্য ব্রান্ড"],
    cons: ["ইন্টেরিয়র পুরনো"],
    image_url: null,
    is_featured: false,
    display_order: 11,
    created_at: CREATED,
    last_price_update: TODAY,
  },
  {
    id: "local-neta-v",
    brand: "Neta",
    model: "V",
    slug: "neta-v",
    type: "EV",
    price_bdt: 3000000,
    range_km: 401,
    battery_kwh: 38.7,
    charging_time_min: 30,
    zero_to_hundred: 9.9,
    specs: { platform: "HPC", safety: "C-NCAP 5-star", airbags: 4, top_speed_kmh: 130 },
    pros: ["সবচেয়ে সাশ্রয়ী EV", "১১-ইন-১ ADAS"],
    cons: ["সার্ভিস নেটওয়ার্ক ছোট"],
    image_url: null,
    is_featured: false,
    display_order: 12,
    created_at: CREATED,
    last_price_update: TODAY,
  },
  {
    id: "local-zeekr-x",
    brand: "Zeekr",
    model: "X",
    slug: "zeekr-x",
    type: "EV",
    price_bdt: 7500000,
    range_km: 440,
    battery_kwh: 66,
    charging_time_min: 30,
    zero_to_hundred: 3.7,
    specs: { platform: "SEA", safety: "Euro NCAP 5-star", airbags: 7, top_speed_kmh: 180 },
    pros: ["প্রিমিয়াম ইন্টেরিয়র", "SEA প্ল্যাটফর্ম"],
    cons: ["প্রিমিয়াম দাম"],
    image_url: null,
    is_featured: false,
    display_order: 13,
    created_at: CREATED,
    last_price_update: TODAY,
  },
  {
    id: "local-deepal-s07",
    brand: "Deepal",
    model: "S07",
    slug: "deepal-s07",
    type: "EV",
    price_bdt: 8000000,
    range_km: 485,
    battery_kwh: 79.97,
    charging_time_min: 25,
    zero_to_hundred: 5.9,
    specs: { platform: "EPA1", safety: "C-NCAP 5-star", airbags: 6, top_speed_kmh: 170 },
    pros: ["Sunflower স্মার্ট কেবিন"],
    cons: ["নতুন ব্র্যান্ড — সার্ভিস সীমিত"],
    image_url: null,
    is_featured: false,
    display_order: 14,
    created_at: CREATED,
    last_price_update: TODAY,
  },
  {
    id: "local-dongfeng-nano-box",
    brand: "Dongfeng",
    model: "Nano Box",
    slug: "dongfeng-nano-box",
    type: "EV",
    price_bdt: 2500000,
    range_km: 271,
    battery_kwh: 27.2,
    charging_time_min: 30,
    zero_to_hundred: 12.6,
    specs: { platform: "S-EV", safety: "C-NCAP", airbags: 2, top_speed_kmh: 100 },
    pros: ["সবচেয়ে কম দামের ইলেকট্রিক গাড়ি"],
    cons: ["কম রেঞ্জ"],
    image_url: null,
    is_featured: false,
    display_order: 15,
    created_at: CREATED,
    last_price_update: TODAY,
  },
  {
    id: "local-wuling-bingo",
    brand: "Wuling",
    model: "Bingo",
    slug: "wuling-bingo",
    type: "EV",
    price_bdt: 2200000,
    range_km: 333,
    battery_kwh: 31.9,
    charging_time_min: 45,
    zero_to_hundred: 12.0,
    specs: { platform: "GSEV", safety: "C-NCAP", airbags: 2, top_speed_kmh: 100 },
    pros: ["কম দামে শহুরে মবিলিটি"],
    cons: ["হাইওয়েতে অযোগ্য"],
    image_url: null,
    is_featured: false,
    display_order: 16,
    created_at: CREATED,
    last_price_update: TODAY,
  },
];

export const LOCAL_POSTS: Post[] = [
  {
    id: "local-post-1",
    title_en: "BYD Seal price update",
    title_bn: "BYD Seal-এর দাম আপডেট ২০২৬",
    slug: "byd-seal-price-update-2026",
    excerpt_bn: "বাংলাদেশে BYD Seal-এর সর্বশেষ দাম ও ভ্যারিয়েন্ট বিশ্লেষণ।",
    content_en: "Updated BYD Seal pricing in Bangladesh.",
    content_bn: "বাংলাদেশে BYD Seal-এর সর্বশেষ দাম ও ভ্যারিয়েন্ট বিশ্লেষণ।",
    category: "Price Watch",
    meta_title: "BYD Seal price update 2026",
    meta_description: "BYD Seal-এর সর্বশেষ দাম বাংলাদেশে",
    cover_url: null,
    author: "BanglaEV",
    published: true,
    published_at: "2026-09-01T06:00:00Z",
    created_at: "2026-09-01T06:00:00Z",
  },
  {
    id: "local-post-2",
    title_en: "Charging network growth",
    title_bn: "ঢাকায় নতুন ফাস্ট চার্জিং স্টেশন",
    slug: "dhaka-fast-charging-stations-2026",
    excerpt_bn: "ঢাকা-চট্টগ্রাম মহাসড়কে নতুন DC চার্জার।",
    content_en: "New DC chargers along the Dhaka-Chattogram highway.",
    content_bn: "ঢাকা-চট্টগ্রাম মহাসড়কে নতুন DC চার্জার।",
    category: "Charging",
    meta_title: "Dhaka fast charging stations 2026",
    meta_description: "ঢাকায় নতুন ফাস্ট চার্জিং স্টেশন",
    cover_url: null,
    author: "BanglaEV",
    published: true,
    published_at: "2026-08-20T06:00:00Z",
    created_at: "2026-08-20T06:00:00Z",
  },
  {
    id: "local-post-3",
    title_en: "MG 4 review",
    title_bn: "MG 4 রিভিউ: শহুরে EV",
    slug: "mg-4-review-2026",
    excerpt_bn: "MG 4-এর দাম, রেঞ্জ ও রিয়েল-ওয়ার্ল্ড অভিজ্ঞতা।",
    content_en: "MG 4 pricing, range and real-world experience.",
    content_bn: "MG 4-এর দাম, রেঞ্জ ও রিয়েল-ওয়ার্ল্ড অভিজ্ঞতা।",
    category: "Review",
    meta_title: "MG 4 review 2026",
    meta_description: "MG 4 রিভিউ",
    cover_url: null,
    author: "BanglaEV",
    published: true,
    published_at: "2026-08-05T06:00:00Z",
    created_at: "2026-08-05T06:00:00Z",
  },
  {
    id: "local-post-4",
    title_en: "Neta V first look",
    title_bn: "Neta V ফার্স্ট লুক",
    slug: "neta-v-first-look-2026",
    excerpt_bn: "বাংলাদেশের সবচেয়ে সাশ্রয়ী ইলেকট্রিক গাড়ি কেমন?",
    content_en: "First look at Bangladesh's most affordable EV.",
    content_bn: "বাংলাদেশের সবচেয়ে সাশ্রয়ী ইলেকট্রিক গাড়ি কেমন?",
    category: "News",
    meta_title: "Neta V first look 2026",
    meta_description: "Neta V ফার্স্ট লুক",
    cover_url: null,
    author: "BanglaEV",
    published: true,
    published_at: "2026-07-15T06:00:00Z",
    created_at: "2026-07-15T06:00:00Z",
  },
];
