/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ChargingRouteImport } from './routes/charging'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as BydRouteImport } from './routes/byd'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as ModelsIndexRouteImport } from './routes/models.index'
import { Route as BydIndexRouteImport } from './routes/byd.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as ModelsSlugRouteImport } from './routes/models.$slug'
import { Route as GuideBestElectricBikesBangladeshRouteImport } from './routes/guide.best-electric-bikes-bangladesh'
import { Route as BydSlugRouteImport } from './routes/byd.$slug'
import { Route as BrandsBrandRouteImport } from './routes/brands.$brand'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ChargingRoute = ChargingRouteImport.update({
  id: '/charging',
  path: '/charging',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BydRoute = BydRouteImport.update({
  id: '/byd',
  path: '/byd',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModelsRoute,
} as any)
const BydIndexRoute = BydIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BydRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const ModelsSlugRoute = ModelsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ModelsRoute,
} as any)
const GuideBestElectricBikesBangladeshRoute =
  GuideBestElectricBikesBangladeshRouteImport.update({
    id: '/guide/best-electric-bikes-bangladesh',
    path: '/guide/best-electric-bikes-bangladesh',
    getParentRoute: () => rootRouteImport,
  } as any)
const BydSlugRoute = BydSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BydRoute,
} as any)
const BrandsBrandRoute = BrandsBrandRouteImport.update({
  id: '/brands/$brand',
  path: '/brands/$brand',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/byd': typeof BydRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/charging': typeof ChargingRoute
  '/compare': typeof CompareRoute
  '/models': typeof ModelsRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/brands/$brand': typeof BrandsBrandRoute
  '/byd/$slug': typeof BydSlugRoute
  '/guide/best-electric-bikes-bangladesh': typeof GuideBestElectricBikesBangladeshRoute
  '/models/$slug': typeof ModelsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/byd/': typeof BydIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculator': typeof CalculatorRoute
  '/charging': typeof ChargingRoute
  '/compare': typeof CompareRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/brands/$brand': typeof BrandsBrandRoute
  '/byd/$slug': typeof BydSlugRoute
  '/guide/best-electric-bikes-bangladesh': typeof GuideBestElectricBikesBangladeshRoute
  '/models/$slug': typeof ModelsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/byd': typeof BydIndexRoute
  '/models': typeof ModelsIndexRoute
  '/news': typeof NewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/byd': typeof BydRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/charging': typeof ChargingRoute
  '/compare': typeof CompareRoute
  '/models': typeof ModelsRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/brands/$brand': typeof BrandsBrandRoute
  '/byd/$slug': typeof BydSlugRoute
  '/guide/best-electric-bikes-bangladesh': typeof GuideBestElectricBikesBangladeshRoute
  '/models/$slug': typeof ModelsSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/byd/': typeof BydIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/byd'
    | '/calculator'
    | '/charging'
    | '/compare'
    | '/models'
    | '/news'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/brands/$brand'
    | '/byd/$slug'
    | '/guide/best-electric-bikes-bangladesh'
    | '/models/$slug'
    | '/news/$slug'
    | '/byd/'
    | '/models/'
    | '/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calculator'
    | '/charging'
    | '/compare'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/brands/$brand'
    | '/byd/$slug'
    | '/guide/best-electric-bikes-bangladesh'
    | '/models/$slug'
    | '/news/$slug'
    | '/byd'
    | '/models'
    | '/news'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/byd'
    | '/calculator'
    | '/charging'
    | '/compare'
    | '/models'
    | '/news'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/brands/$brand'
    | '/byd/$slug'
    | '/guide/best-electric-bikes-bangladesh'
    | '/models/$slug'
    | '/news/$slug'
    | '/byd/'
    | '/models/'
    | '/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BydRoute: typeof BydRouteWithChildren
  CalculatorRoute: typeof CalculatorRoute
  ChargingRoute: typeof ChargingRoute
  CompareRoute: typeof CompareRoute
  ModelsRoute: typeof ModelsRouteWithChildren
  NewsRoute: typeof NewsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BrandsBrandRoute: typeof BrandsBrandRoute
  GuideBestElectricBikesBangladeshRoute: typeof GuideBestElectricBikesBangladeshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charging': {
      id: '/charging'
      path: '/charging'
      fullPath: '/charging'
      preLoaderRoute: typeof ChargingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/byd': {
      id: '/byd'
      path: '/byd'
      fullPath: '/byd'
      preLoaderRoute: typeof BydRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/models/': {
      id: '/models/'
      path: '/'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof ModelsRoute
    }
    '/byd/': {
      id: '/byd/'
      path: '/'
      fullPath: '/byd/'
      preLoaderRoute: typeof BydIndexRouteImport
      parentRoute: typeof BydRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/models/$slug': {
      id: '/models/$slug'
      path: '/$slug'
      fullPath: '/models/$slug'
      preLoaderRoute: typeof ModelsSlugRouteImport
      parentRoute: typeof ModelsRoute
    }
    '/guide/best-electric-bikes-bangladesh': {
      id: '/guide/best-electric-bikes-bangladesh'
      path: '/guide/best-electric-bikes-bangladesh'
      fullPath: '/guide/best-electric-bikes-bangladesh'
      preLoaderRoute: typeof GuideBestElectricBikesBangladeshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/byd/$slug': {
      id: '/byd/$slug'
      path: '/$slug'
      fullPath: '/byd/$slug'
      preLoaderRoute: typeof BydSlugRouteImport
      parentRoute: typeof BydRoute
    }
    '/brands/$brand': {
      id: '/brands/$brand'
      path: '/brands/$brand'
      fullPath: '/brands/$brand'
      preLoaderRoute: typeof BrandsBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BydRouteChildren {
  BydSlugRoute: typeof BydSlugRoute
  BydIndexRoute: typeof BydIndexRoute
}

const BydRouteChildren: BydRouteChildren = {
  BydSlugRoute: BydSlugRoute,
  BydIndexRoute: BydIndexRoute,
}

const BydRouteWithChildren = BydRoute._addFileChildren(BydRouteChildren)

interface ModelsRouteChildren {
  ModelsSlugRoute: typeof ModelsSlugRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
}

const ModelsRouteChildren: ModelsRouteChildren = {
  ModelsSlugRoute: ModelsSlugRoute,
  ModelsIndexRoute: ModelsIndexRoute,
}

const ModelsRouteWithChildren =
  ModelsRoute._addFileChildren(ModelsRouteChildren)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BydRoute: BydRouteWithChildren,
  CalculatorRoute: CalculatorRoute,
  ChargingRoute: ChargingRoute,
  CompareRoute: CompareRoute,
  ModelsRoute: ModelsRouteWithChildren,
  NewsRoute: NewsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BrandsBrandRoute: BrandsBrandRoute,
  GuideBestElectricBikesBangladeshRoute: GuideBestElectricBikesBangladeshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
